version: "3.9"

services:
  web:
    image: flask-projem-web:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: flask_app
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    secrets:
      - mysql_root_password

networks:
  appnet:

volumes:
  db_data:

secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
